on:
  pull_request:
    branches: [ "master", "main" ]

  push:
    branches: [ "master", "main" ]

jobs:
  check_data_models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data_model_file: [
          'PRIMED_phenotype_data_model.json',
          'PRIMED_genotype_data_model.json',
          'PRIMED_GSR_data_model.json'
        ]
    name: Check data model
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.3"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: github::UW-GAC/AnvilDataModels, any::sessioninfo
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Check ${{ matrix.data_model_file }} file
        run: |
          AnvilDataModels::json_to_dm("${{ matrix.data_model_file }}")
        shell: Rscript {0}

  check_test_data:
    runs-on: ubuntu-latest
    name: Check test model
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cromwell
        uses: broadinstitute/cromwell/set_up_cromwell_action@87
        with:
          cromwell-version: "latest"

      - name: Success
        run: echo "Success!"
